name: core
description: Core Module for TheCocktailApp
version: 0.0.1
author: Ricardo J. Chamorro
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^3.0.6
  # state management
  stacked: ^2.0.2
  # navigation
  auto_route: ^4.0.1
  # logger
  logger: ^1.0.0
  # inversion of control
  get_it: ^7.2.0
  injectable: ^1.2.2
  adaptive_dialog: ^1.3.0
  stacked_hooks: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator:
  injectable_generator:

flutter: