name: domain
description: Domain Module for TheCocktailApp
version: 0.0.1
author: Ricardo J. Chamorro

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # inversion of control
  get_it: ^7.2.0
  injectable: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  injectable_generator:

flutter: